all:
	./cuda_password_crack > 1.txt	
	./cuda_password_crack > 2.txt	
	./cuda_password_crack > 3.txt	
	./cuda_password_crack > 4.txt	
	./cuda_password_crack > 5.txt	
	./cuda_password_crack > 6.txt	
	./cuda_password_crack > 7.txt	
	./cuda_password_crack > 8.txt	
	./cuda_password_crack > 9.txt	
	./cuda_password_crack > 10.txt	
	
	
